### ISSUE TITLE
Allow aggregate maps for more than one property at a time

### ISSUE THREAD

**Issue by jorgesicachanr** [equinor/ccs-scripts#170]
Currently only definition of properties to get aggregate maps is only possible this way

```
input:
  grid: "tests/data/reek_3d_maps/REEK.EGRID"
  properties:
    - source: "tests/data/reek_3d_maps/REEK.UNRST"
      name: "SWAT"
      lower_threshold: 1e-12
```

It should be possible to generate aggregate maps for more than one property at a time. Should work similarly as for migration time maps. See https://github.com/equinor/ccs-scripts/issues/8.
